extract:
    pull:
        type: file
        uri: ./data_in.csv
    read:
        format: csv
        options:
            separator: ","
            enclosure: '"'
            trim: true
            header: true

transform:
    type: expressive
    mapping:
        out.name: in.Name
        out.sex: in.Sex
        out.years_count: 'in.Age * 100'

load:
    write:
        format: json
    push:
        type: file
        uri: ./data_out.json
