parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Jrmgx\Etl\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
