name: run-job
on: workflow_dispatch

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run job
        uses: docker://php:8.1-cli-alpine
        run:
          - cd App
          - php composer.phar install
          - php bin/console etl:run
          - cat ../data_out.json
