name: run-job
on: workflow_dispatch

permissions:
  contents: read

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: app/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('app/composer.lock') }}
      - name: Run
        run: |
          cd app
          php composer.phar install
          php bin/console etl:run
